CXX = g++
CXXFLAGS = -Wall -Wextra -std=c++17


LIBSFML = -lsfml-graphics -lsfml-window -lsfml-system
LIBSQLITE = -lsqlite3
LIBBOOST = -lboost_system -lboost_filesystem


LIB_DIR = libs
LIBS = $(LIB_DIR)/libpoint.a $(LIB_DIR)/libboard.a $(LIB_DIR)/libpainter.a $(LIB_DIR)/libsnake.a


SRC_DIR = src
INCLUDE_DIR = include
SRC = $(wildcard $(SRC_DIR)/*.cpp)
OBJ = $(SRC:.cpp=.o)


EXEC = game


$(LIB_DIR)/libpoint.a: $(SRC_DIR)/point.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $(SRC_DIR)/point.o
	ar rcs $@ $(SRC_DIR)/point.o

$(LIB_DIR)/libboard.a: $(SRC_DIR)/board.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $(SRC_DIR)/board.o
	ar rcs $@ $(SRC_DIR)/board.o

$(LIB_DIR)/libsnake.a: $(SRC_DIR)/snake.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $(SRC_DIR)/snake.o
	ar rcs $@ $(SRC_DIR)/snake.o

$(LIB_DIR)/libpainter.a: $(SRC_DIR)/painter.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $(SRC_DIR)/painter.o
	ar rcs $@ $(SRC_DIR)/painter.o

# Target principal
$(EXEC): $(OBJ) $(LIBS)
	$(CXX) $(CXXFLAGS) -o $@ $(OBJ) $(LIBS) $(LIBSFML) $(LIBSQLITE) $(LIBBOOST)

# Curățare fișiere temporare
clean:
	rm -f $(SRC_DIR)/*.o $(LIB_DIR)/*.a $(EXEC)

.PHONY: clean all
